export default{
    artists: '/artists/',
    calendar: '/calendar/',
    artistCalendar: '/artist/calendar/',
    eventlocation: '/eventlocation/',
    login: '/api/login/',
    offer: '/offer/',
    artistOffers: '/artist/offers/',
    customerOffers: '/customer/offers/',
    customerPersonalInformation: '/customer/personalInformation/',
    artistPersonalInformation: '/artist/personalInformation/',
    portfolio: '/portfolio/',
    paymentPackages: '/artist/paymentPackages/',
    paymentPackage: '/paymentPackage/',
    custom: '/custom/',
    registerCustomer: '/signupCustomer/',
    registerArtist: '/signupArtist/',
    customer: '/customer/',
    artist: '/artist/',
    paymentCode:'/paymentCode/',
    artistPayPackage: '/artist/paymentPackages/',
    performance: '/performance/',
    fare: '/fare/',
    zones: '/zones/',
    rating: '/customer/rating/',
    genres: '/artisticGenders/',
    
}