export default{
    artists: '/artists/',
    calendar: '/calendar/',
    eventlocation: '/eventlocation/',
    login: '/api/login/',
    offer: '/offer/',
    artistOffers: '/artist/offers/',
    customerOffers: '/customer/offers/',
    offer: '/offer/',
    customerPersonalInformation: '/customer/personalInformation/',
    artistPersonalInformation: '/artist/personalInformation/',
    portfolio: '/portfolio/',
    paymentPackages: '/artist/paymentPackages/',
    paymentPackage: '/paymentPackage/',
    custom: '/custom/',
}