export default{
    artists: '/artists/',
    calendar: '/calendar/',
    eventlocation: '/eventlocation/',
    login: '/api/login/',
    offer: '/offer/',
    artistOffers: '/artist/offers/',
    customerOffers: '/customer/offers/',
    customerPersonalInformation: '/customer/personalInformation/',
    artistPersonalInformation: '/artist/personalInformation/',
    portfolio: '/portfolio/',
    registerCustomer: '/signupCustomer/',
    registerArtist: '/signupArtist/',
    customer: '/customer/',
    artist: '/artist/',
    paymentCode:'/paymentCode/',
    artistPayPackage: '/artist/paymentPackages/', 
}